//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCACSLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carreras
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carreras()
        {
            this.Indicadores_archivos = new HashSet<Indicadores_archivos>();
            this.Indicadores_detalle = new HashSet<Indicadores_detalle>();
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int IdCarrera { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Clave { get; set; }
        public string Ini { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicadores_archivos> Indicadores_archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicadores_detalle> Indicadores_detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
