//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCACSLA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Indicadores
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Indicadores()
        {
            this.Indicadores_archivos = new HashSet<Indicadores_archivos>();
            this.Indicadores_detalle = new HashSet<Indicadores_detalle>();
        }
    
        public int IdEstandar { get; set; }
        public int IdVariable { get; set; }
        public string DescripcionEstandar { get; set; }
        public string DescripcionVariable { get; set; }
        public int Referente { get; set; }
        public string DescripcionReferente { get; set; }
        public string Anexo { get; set; }
        public int ValorMax { get; set; }
        public int ValorObt { get; set; }
        public int IdCoordinacion { get; set; }
        public Nullable<bool> Observado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicadores_archivos> Indicadores_archivos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Indicadores_detalle> Indicadores_detalle { get; set; }
    }
}
