//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcCACSLA.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DB_9F6318_fcacacslav2Entities1 : DbContext
    {
        public DB_9F6318_fcacacslav2Entities1()
            : base("name=DB_9F6318_fcacacslav2Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Carreras> Carreras { get; set; }
        public virtual DbSet<Indicadores> Indicadores { get; set; }
        public virtual DbSet<Indicadores_archivos> Indicadores_archivos { get; set; }
        public virtual DbSet<Indicadores_detalle> Indicadores_detalle { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Usuarios_niveles> Usuarios_niveles { get; set; }
        public virtual DbSet<Coordinaciones> Coordinaciones { get; set; }
    
        public virtual ObjectResult<usp_Estandar_1_GetVariable_Archivos_Result> usp_Estandar_1_GetVariable_Archivos(string parametro, Nullable<int> carrera)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            var carreraParameter = carrera.HasValue ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Estandar_1_GetVariable_Archivos_Result>("usp_Estandar_1_GetVariable_Archivos", parametroParameter, carreraParameter);
        }
    
        public virtual ObjectResult<usp_Estandar_1_GetVariable_Archivos_Result> usp_Estandar_GetVariables_Archivos(string parametro, Nullable<int> carrera)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            var carreraParameter = carrera.HasValue ?
                new ObjectParameter("carrera", carrera) :
                new ObjectParameter("carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Estandar_1_GetVariable_Archivos_Result>("usp_Estandar_GetVariables_Archivos", parametroParameter, carreraParameter);
        }
    }
}
